inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/*
    - config/initializers/*
    - db/migrate/*
    - db/schema.rb
    - db/seeds.rb
    - spec/spec_helper.rb

Rails:
  Enabled: true

Documentation:
  Enabled: false

DotPosition:
  EnforcedStyle: trailing

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundMethodBody:
  Enabled: false
Metrics/BlockLength:
    Exclude:
      - 'Rakefile'
      - '**/*.rake'
      - 'spec/**/*.rb'
